/**
* Riot API
*  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## Download OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([download file](../openapi-3.0.0.json), [view ui](?openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([download file](../openapi-3.0.0.min.json), [view ui](?openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([download file](../openapi-3.0.0.yml), [view ui](?openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([download file](../openapi-3.0.0.min.yml), [view ui](?openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([download file](../swaggerspec-2.0.json), [view ui](?swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([download file](../swaggerspec-2.0.min.json), [view ui](?swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([download file](../swaggerspec-2.0.yml), [view ui](?swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([download file](../swaggerspec-2.0.min.yml), [view ui](?swaggerspec-2.0.min.yml)) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.org/MingweiSamuel/riotapi-schema/builds) daily. *** 
*
* OpenAPI spec version: dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package io.swagger.client.models

import io.swagger.client.models.MatchMinusv4MatchPositionDto

import com.squareup.moshi.Json
/**
 * 
 * @param eventType 
 * @param towerType 
 * @param teamId 
 * @param ascendedType 
 * @param killerId 
 * @param levelUpType 
 * @param pointCaptured 
 * @param assistingParticipantIds 
 * @param wardType 
 * @param monsterType 
 * @param type (Legal values:  CHAMPION_KILL,  WARD_PLACED,  WARD_KILL,  BUILDING_KILL,  ELITE_MONSTER_KILL,  ITEM_PURCHASED,  ITEM_SOLD,  ITEM_DESTROYED,  ITEM_UNDO,  SKILL_LEVEL_UP,  ASCENDED_EVENT,  CAPTURE_POINT,  PORO_KING_SUMMON)
 * @param skillSlot 
 * @param victimId 
 * @param timestamp 
 * @param afterId 
 * @param monsterSubType 
 * @param laneType 
 * @param itemId 
 * @param participantId 
 * @param buildingType 
 * @param creatorId 
 * @param position 
 * @param beforeId 
 */
data class MatchMinusv4MatchEventDto (
    val eventType: kotlin.String? = null,
    val towerType: kotlin.String? = null,
    val teamId: kotlin.Int? = null,
    val ascendedType: kotlin.String? = null,
    val killerId: kotlin.Int? = null,
    val levelUpType: kotlin.String? = null,
    val pointCaptured: kotlin.String? = null,
    val assistingParticipantIds: kotlin.Array<kotlin.Int>? = null,
    val wardType: kotlin.String? = null,
    val monsterType: kotlin.String? = null,
    /* (Legal values:  CHAMPION_KILL,  WARD_PLACED,  WARD_KILL,  BUILDING_KILL,  ELITE_MONSTER_KILL,  ITEM_PURCHASED,  ITEM_SOLD,  ITEM_DESTROYED,  ITEM_UNDO,  SKILL_LEVEL_UP,  ASCENDED_EVENT,  CAPTURE_POINT,  PORO_KING_SUMMON) */
    val type: MatchMinusv4MatchEventDto.Type? = null,
    val skillSlot: kotlin.Int? = null,
    val victimId: kotlin.Int? = null,
    val timestamp: kotlin.Long? = null,
    val afterId: kotlin.Int? = null,
    val monsterSubType: kotlin.String? = null,
    val laneType: kotlin.String? = null,
    val itemId: kotlin.Int? = null,
    val participantId: kotlin.Int? = null,
    val buildingType: kotlin.String? = null,
    val creatorId: kotlin.Int? = null,
    val position: MatchMinusv4MatchPositionDto? = null,
    val beforeId: kotlin.Int? = null
) {

    /**
    * (Legal values:  CHAMPION_KILL,  WARD_PLACED,  WARD_KILL,  BUILDING_KILL,  ELITE_MONSTER_KILL,  ITEM_PURCHASED,  ITEM_SOLD,  ITEM_DESTROYED,  ITEM_UNDO,  SKILL_LEVEL_UP,  ASCENDED_EVENT,  CAPTURE_POINT,  PORO_KING_SUMMON)
    * Values: cHAMPIONKILL,wARDPLACED,wARDKILL,bUILDINGKILL,eLITEMONSTERKILL,iTEMPURCHASED,iTEMSOLD,iTEMDESTROYED,iTEMUNDO,sKILLLEVELUP,aSCENDEDEVENT,cAPTUREPOINT,pOROKINGSUMMON
    */
    enum class Type(val value: kotlin.String){
    
        @Json(name = "CHAMPION_KILL") cHAMPIONKILL("CHAMPION_KILL"),
    
        @Json(name = "WARD_PLACED") wARDPLACED("WARD_PLACED"),
    
        @Json(name = "WARD_KILL") wARDKILL("WARD_KILL"),
    
        @Json(name = "BUILDING_KILL") bUILDINGKILL("BUILDING_KILL"),
    
        @Json(name = "ELITE_MONSTER_KILL") eLITEMONSTERKILL("ELITE_MONSTER_KILL"),
    
        @Json(name = "ITEM_PURCHASED") iTEMPURCHASED("ITEM_PURCHASED"),
    
        @Json(name = "ITEM_SOLD") iTEMSOLD("ITEM_SOLD"),
    
        @Json(name = "ITEM_DESTROYED") iTEMDESTROYED("ITEM_DESTROYED"),
    
        @Json(name = "ITEM_UNDO") iTEMUNDO("ITEM_UNDO"),
    
        @Json(name = "SKILL_LEVEL_UP") sKILLLEVELUP("SKILL_LEVEL_UP"),
    
        @Json(name = "ASCENDED_EVENT") aSCENDEDEVENT("ASCENDED_EVENT"),
    
        @Json(name = "CAPTURE_POINT") cAPTUREPOINT("CAPTURE_POINT"),
    
        @Json(name = "PORO_KING_SUMMON") pOROKINGSUMMON("PORO_KING_SUMMON");
    
    }

}

