<?php
/**
 * LeagueV4LeagueItemDTO
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Riot API
 *
 * OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## Download OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([download file](../openapi-3.0.0.json), [view ui](?openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([download file](../openapi-3.0.0.min.json), [view ui](?openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([download file](../openapi-3.0.0.yml), [view ui](?openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([download file](../openapi-3.0.0.min.yml), [view ui](?openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([download file](../swaggerspec-2.0.json), [view ui](?swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([download file](../swaggerspec-2.0.min.json), [view ui](?swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([download file](../swaggerspec-2.0.yml), [view ui](?swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([download file](../swaggerspec-2.0.min.yml), [view ui](?swaggerspec-2.0.min.yml)) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.org/MingweiSamuel/riotapi-schema/builds) daily. ***
 *
 * OpenAPI spec version: dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * LeagueV4LeagueItemDTO Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class LeagueV4LeagueItemDTO implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'league-v4.LeagueItemDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'summoner_name' => 'string',
        'hot_streak' => 'bool',
        'mini_series' => '\Swagger\Client\Model\LeagueV4MiniSeriesDTO',
        'wins' => 'int',
        'veteran' => 'bool',
        'losses' => 'int',
        'fresh_blood' => 'bool',
        'inactive' => 'bool',
        'rank' => 'string',
        'summoner_id' => 'string',
        'league_points' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'summoner_name' => null,
        'hot_streak' => null,
        'mini_series' => null,
        'wins' => 'int32',
        'veteran' => null,
        'losses' => 'int32',
        'fresh_blood' => null,
        'inactive' => null,
        'rank' => null,
        'summoner_id' => null,
        'league_points' => 'int32'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'summoner_name' => 'summonerName',
        'hot_streak' => 'hotStreak',
        'mini_series' => 'miniSeries',
        'wins' => 'wins',
        'veteran' => 'veteran',
        'losses' => 'losses',
        'fresh_blood' => 'freshBlood',
        'inactive' => 'inactive',
        'rank' => 'rank',
        'summoner_id' => 'summonerId',
        'league_points' => 'leaguePoints'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'summoner_name' => 'setSummonerName',
        'hot_streak' => 'setHotStreak',
        'mini_series' => 'setMiniSeries',
        'wins' => 'setWins',
        'veteran' => 'setVeteran',
        'losses' => 'setLosses',
        'fresh_blood' => 'setFreshBlood',
        'inactive' => 'setInactive',
        'rank' => 'setRank',
        'summoner_id' => 'setSummonerId',
        'league_points' => 'setLeaguePoints'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'summoner_name' => 'getSummonerName',
        'hot_streak' => 'getHotStreak',
        'mini_series' => 'getMiniSeries',
        'wins' => 'getWins',
        'veteran' => 'getVeteran',
        'losses' => 'getLosses',
        'fresh_blood' => 'getFreshBlood',
        'inactive' => 'getInactive',
        'rank' => 'getRank',
        'summoner_id' => 'getSummonerId',
        'league_points' => 'getLeaguePoints'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['summoner_name'] = isset($data['summoner_name']) ? $data['summoner_name'] : null;
        $this->container['hot_streak'] = isset($data['hot_streak']) ? $data['hot_streak'] : null;
        $this->container['mini_series'] = isset($data['mini_series']) ? $data['mini_series'] : null;
        $this->container['wins'] = isset($data['wins']) ? $data['wins'] : null;
        $this->container['veteran'] = isset($data['veteran']) ? $data['veteran'] : null;
        $this->container['losses'] = isset($data['losses']) ? $data['losses'] : null;
        $this->container['fresh_blood'] = isset($data['fresh_blood']) ? $data['fresh_blood'] : null;
        $this->container['inactive'] = isset($data['inactive']) ? $data['inactive'] : null;
        $this->container['rank'] = isset($data['rank']) ? $data['rank'] : null;
        $this->container['summoner_id'] = isset($data['summoner_id']) ? $data['summoner_id'] : null;
        $this->container['league_points'] = isset($data['league_points']) ? $data['league_points'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets summoner_name
     *
     * @return string
     */
    public function getSummonerName()
    {
        return $this->container['summoner_name'];
    }

    /**
     * Sets summoner_name
     *
     * @param string $summoner_name summoner_name
     *
     * @return $this
     */
    public function setSummonerName($summoner_name)
    {
        $this->container['summoner_name'] = $summoner_name;

        return $this;
    }

    /**
     * Gets hot_streak
     *
     * @return bool
     */
    public function getHotStreak()
    {
        return $this->container['hot_streak'];
    }

    /**
     * Sets hot_streak
     *
     * @param bool $hot_streak hot_streak
     *
     * @return $this
     */
    public function setHotStreak($hot_streak)
    {
        $this->container['hot_streak'] = $hot_streak;

        return $this;
    }

    /**
     * Gets mini_series
     *
     * @return \Swagger\Client\Model\LeagueV4MiniSeriesDTO
     */
    public function getMiniSeries()
    {
        return $this->container['mini_series'];
    }

    /**
     * Sets mini_series
     *
     * @param \Swagger\Client\Model\LeagueV4MiniSeriesDTO $mini_series mini_series
     *
     * @return $this
     */
    public function setMiniSeries($mini_series)
    {
        $this->container['mini_series'] = $mini_series;

        return $this;
    }

    /**
     * Gets wins
     *
     * @return int
     */
    public function getWins()
    {
        return $this->container['wins'];
    }

    /**
     * Sets wins
     *
     * @param int $wins wins
     *
     * @return $this
     */
    public function setWins($wins)
    {
        $this->container['wins'] = $wins;

        return $this;
    }

    /**
     * Gets veteran
     *
     * @return bool
     */
    public function getVeteran()
    {
        return $this->container['veteran'];
    }

    /**
     * Sets veteran
     *
     * @param bool $veteran veteran
     *
     * @return $this
     */
    public function setVeteran($veteran)
    {
        $this->container['veteran'] = $veteran;

        return $this;
    }

    /**
     * Gets losses
     *
     * @return int
     */
    public function getLosses()
    {
        return $this->container['losses'];
    }

    /**
     * Sets losses
     *
     * @param int $losses losses
     *
     * @return $this
     */
    public function setLosses($losses)
    {
        $this->container['losses'] = $losses;

        return $this;
    }

    /**
     * Gets fresh_blood
     *
     * @return bool
     */
    public function getFreshBlood()
    {
        return $this->container['fresh_blood'];
    }

    /**
     * Sets fresh_blood
     *
     * @param bool $fresh_blood fresh_blood
     *
     * @return $this
     */
    public function setFreshBlood($fresh_blood)
    {
        $this->container['fresh_blood'] = $fresh_blood;

        return $this;
    }

    /**
     * Gets inactive
     *
     * @return bool
     */
    public function getInactive()
    {
        return $this->container['inactive'];
    }

    /**
     * Sets inactive
     *
     * @param bool $inactive inactive
     *
     * @return $this
     */
    public function setInactive($inactive)
    {
        $this->container['inactive'] = $inactive;

        return $this;
    }

    /**
     * Gets rank
     *
     * @return string
     */
    public function getRank()
    {
        return $this->container['rank'];
    }

    /**
     * Sets rank
     *
     * @param string $rank rank
     *
     * @return $this
     */
    public function setRank($rank)
    {
        $this->container['rank'] = $rank;

        return $this;
    }

    /**
     * Gets summoner_id
     *
     * @return string
     */
    public function getSummonerId()
    {
        return $this->container['summoner_id'];
    }

    /**
     * Sets summoner_id
     *
     * @param string $summoner_id Player's summonerId (Encrypted)
     *
     * @return $this
     */
    public function setSummonerId($summoner_id)
    {
        $this->container['summoner_id'] = $summoner_id;

        return $this;
    }

    /**
     * Gets league_points
     *
     * @return int
     */
    public function getLeaguePoints()
    {
        return $this->container['league_points'];
    }

    /**
     * Sets league_points
     *
     * @param int $league_points league_points
     *
     * @return $this
     */
    public function setLeaguePoints($league_points)
    {
        $this->container['league_points'] = $league_points;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


