/**
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## Download OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([download file](../openapi-3.0.0.json), [view ui](?openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([download file](../openapi-3.0.0.min.json), [view ui](?openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([download file](../openapi-3.0.0.yml), [view ui](?openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([download file](../openapi-3.0.0.min.yml), [view ui](?openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([download file](../swaggerspec-2.0.json), [view ui](?swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([download file](../swaggerspec-2.0.min.json), [view ui](?swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([download file](../swaggerspec-2.0.yml), [view ui](?swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([download file](../swaggerspec-2.0.min.yml), [view ui](?swaggerspec-2.0.min.yml)) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.org/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * OpenAPI spec version: dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/MatchV4ParticipantDto', 'model/MatchV4ParticipantIdentityDto', 'model/MatchV4TeamStatsDto'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MatchV4ParticipantDto'), require('./MatchV4ParticipantIdentityDto'), require('./MatchV4TeamStatsDto'));
  } else {
    // Browser globals (root is window)
    if (!root.RiotApi) {
      root.RiotApi = {};
    }
    root.RiotApi.MatchV4MatchDto = factory(root.RiotApi.ApiClient, root.RiotApi.MatchV4ParticipantDto, root.RiotApi.MatchV4ParticipantIdentityDto, root.RiotApi.MatchV4TeamStatsDto);
  }
}(this, function(ApiClient, MatchV4ParticipantDto, MatchV4ParticipantIdentityDto, MatchV4TeamStatsDto) {
  'use strict';




  /**
   * The MatchV4MatchDto model module.
   * @module model/MatchV4MatchDto
   * @version dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
   */

  /**
   * Constructs a new <code>MatchV4MatchDto</code>.
   * @alias module:model/MatchV4MatchDto
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>MatchV4MatchDto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/MatchV4MatchDto} obj Optional instance to populate.
   * @return {module:model/MatchV4MatchDto} The populated <code>MatchV4MatchDto</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('seasonId')) {
        obj['seasonId'] = ApiClient.convertToType(data['seasonId'], 'Number');
      }
      if (data.hasOwnProperty('queueId')) {
        obj['queueId'] = ApiClient.convertToType(data['queueId'], 'Number');
      }
      if (data.hasOwnProperty('gameId')) {
        obj['gameId'] = ApiClient.convertToType(data['gameId'], 'Number');
      }
      if (data.hasOwnProperty('participantIdentities')) {
        obj['participantIdentities'] = ApiClient.convertToType(data['participantIdentities'], [MatchV4ParticipantIdentityDto]);
      }
      if (data.hasOwnProperty('gameVersion')) {
        obj['gameVersion'] = ApiClient.convertToType(data['gameVersion'], 'String');
      }
      if (data.hasOwnProperty('platformId')) {
        obj['platformId'] = ApiClient.convertToType(data['platformId'], 'String');
      }
      if (data.hasOwnProperty('gameMode')) {
        obj['gameMode'] = ApiClient.convertToType(data['gameMode'], 'String');
      }
      if (data.hasOwnProperty('mapId')) {
        obj['mapId'] = ApiClient.convertToType(data['mapId'], 'Number');
      }
      if (data.hasOwnProperty('gameType')) {
        obj['gameType'] = ApiClient.convertToType(data['gameType'], 'String');
      }
      if (data.hasOwnProperty('teams')) {
        obj['teams'] = ApiClient.convertToType(data['teams'], [MatchV4TeamStatsDto]);
      }
      if (data.hasOwnProperty('participants')) {
        obj['participants'] = ApiClient.convertToType(data['participants'], [MatchV4ParticipantDto]);
      }
      if (data.hasOwnProperty('gameDuration')) {
        obj['gameDuration'] = ApiClient.convertToType(data['gameDuration'], 'Number');
      }
      if (data.hasOwnProperty('gameCreation')) {
        obj['gameCreation'] = ApiClient.convertToType(data['gameCreation'], 'Number');
      }
    }
    return obj;
  }

  /**
   * Please refer to the Game Constants documentation.
   * @member {Number} seasonId
   */
  exports.prototype['seasonId'] = undefined;
  /**
   * Please refer to the Game Constants documentation.
   * @member {Number} queueId
   */
  exports.prototype['queueId'] = undefined;
  /**
   * @member {Number} gameId
   */
  exports.prototype['gameId'] = undefined;
  /**
   * Participant identity information.
   * @member {Array.<module:model/MatchV4ParticipantIdentityDto>} participantIdentities
   */
  exports.prototype['participantIdentities'] = undefined;
  /**
   * The major.minor version typically indicates the patch the match was played on.
   * @member {String} gameVersion
   */
  exports.prototype['gameVersion'] = undefined;
  /**
   * Platform where the match was played.
   * @member {String} platformId
   */
  exports.prototype['platformId'] = undefined;
  /**
   * Please refer to the Game Constants documentation.
   * @member {String} gameMode
   */
  exports.prototype['gameMode'] = undefined;
  /**
   * Please refer to the Game Constants documentation.
   * @member {Number} mapId
   */
  exports.prototype['mapId'] = undefined;
  /**
   * Please refer to the Game Constants documentation.
   * @member {String} gameType
   */
  exports.prototype['gameType'] = undefined;
  /**
   * Team information.
   * @member {Array.<module:model/MatchV4TeamStatsDto>} teams
   */
  exports.prototype['teams'] = undefined;
  /**
   * Participant information.
   * @member {Array.<module:model/MatchV4ParticipantDto>} participants
   */
  exports.prototype['participants'] = undefined;
  /**
   * Match duration in seconds.
   * @member {Number} gameDuration
   */
  exports.prototype['gameDuration'] = undefined;
  /**
   * Designates the timestamp when champion select ended and the loading screen appeared, NOT when the game timer was at 0:00.
   * @member {Number} gameCreation
   */
  exports.prototype['gameCreation'] = undefined;



  return exports;
}));


