<?php
/**
 * MatchV4MatchDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Riot API
 *
 * OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## Download OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([download file](../openapi-3.0.0.json), [view ui](?openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([download file](../openapi-3.0.0.min.json), [view ui](?openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([download file](../openapi-3.0.0.yml), [view ui](?openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([download file](../openapi-3.0.0.min.yml), [view ui](?openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([download file](../swaggerspec-2.0.json), [view ui](?swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([download file](../swaggerspec-2.0.min.json), [view ui](?swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([download file](../swaggerspec-2.0.yml), [view ui](?swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([download file](../swaggerspec-2.0.min.yml), [view ui](?swaggerspec-2.0.min.yml)) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.org/MingweiSamuel/riotapi-schema/builds) daily. ***
 *
 * OpenAPI spec version: dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.7
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MatchV4MatchDtoTest Class Doc Comment
 *
 * @category    Class
 * @description MatchV4MatchDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MatchV4MatchDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "MatchV4MatchDto"
     */
    public function testMatchV4MatchDto()
    {
    }

    /**
     * Test attribute "season_id"
     */
    public function testPropertySeasonId()
    {
    }

    /**
     * Test attribute "queue_id"
     */
    public function testPropertyQueueId()
    {
    }

    /**
     * Test attribute "game_id"
     */
    public function testPropertyGameId()
    {
    }

    /**
     * Test attribute "participant_identities"
     */
    public function testPropertyParticipantIdentities()
    {
    }

    /**
     * Test attribute "game_version"
     */
    public function testPropertyGameVersion()
    {
    }

    /**
     * Test attribute "platform_id"
     */
    public function testPropertyPlatformId()
    {
    }

    /**
     * Test attribute "game_mode"
     */
    public function testPropertyGameMode()
    {
    }

    /**
     * Test attribute "map_id"
     */
    public function testPropertyMapId()
    {
    }

    /**
     * Test attribute "game_type"
     */
    public function testPropertyGameType()
    {
    }

    /**
     * Test attribute "teams"
     */
    public function testPropertyTeams()
    {
    }

    /**
     * Test attribute "participants"
     */
    public function testPropertyParticipants()
    {
    }

    /**
     * Test attribute "game_duration"
     */
    public function testPropertyGameDuration()
    {
    }

    /**
     * Test attribute "game_creation"
     */
    public function testPropertyGameCreation()
    {
    }
}
