/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## Download OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([download file](../openapi-3.0.0.json), [view ui](?openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([download file](../openapi-3.0.0.min.json), [view ui](?openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([download file](../openapi-3.0.0.yml), [view ui](?openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([download file](../openapi-3.0.0.min.yml), [view ui](?openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([download file](../swaggerspec-2.0.json), [view ui](?swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([download file](../swaggerspec-2.0.min.json), [view ui](?swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([download file](../swaggerspec-2.0.yml), [view ui](?swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([download file](../swaggerspec-2.0.min.yml), [view ui](?swaggerspec-2.0.min.yml)) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.org/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * OpenAPI spec version: dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ChampionV3ChampionInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-17T15:57:39.031+02:00")
public class ChampionV3ChampionInfo {
  @SerializedName("freeChampionIdsForNewPlayers")
  private List<Integer> freeChampionIdsForNewPlayers = null;

  @SerializedName("freeChampionIds")
  private List<Integer> freeChampionIds = null;

  @SerializedName("maxNewPlayerLevel")
  private Integer maxNewPlayerLevel = null;

  public ChampionV3ChampionInfo freeChampionIdsForNewPlayers(List<Integer> freeChampionIdsForNewPlayers) {
    this.freeChampionIdsForNewPlayers = freeChampionIdsForNewPlayers;
    return this;
  }

  public ChampionV3ChampionInfo addFreeChampionIdsForNewPlayersItem(Integer freeChampionIdsForNewPlayersItem) {
    if (this.freeChampionIdsForNewPlayers == null) {
      this.freeChampionIdsForNewPlayers = new ArrayList<Integer>();
    }
    this.freeChampionIdsForNewPlayers.add(freeChampionIdsForNewPlayersItem);
    return this;
  }

   /**
   * Get freeChampionIdsForNewPlayers
   * @return freeChampionIdsForNewPlayers
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getFreeChampionIdsForNewPlayers() {
    return freeChampionIdsForNewPlayers;
  }

  public void setFreeChampionIdsForNewPlayers(List<Integer> freeChampionIdsForNewPlayers) {
    this.freeChampionIdsForNewPlayers = freeChampionIdsForNewPlayers;
  }

  public ChampionV3ChampionInfo freeChampionIds(List<Integer> freeChampionIds) {
    this.freeChampionIds = freeChampionIds;
    return this;
  }

  public ChampionV3ChampionInfo addFreeChampionIdsItem(Integer freeChampionIdsItem) {
    if (this.freeChampionIds == null) {
      this.freeChampionIds = new ArrayList<Integer>();
    }
    this.freeChampionIds.add(freeChampionIdsItem);
    return this;
  }

   /**
   * Get freeChampionIds
   * @return freeChampionIds
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getFreeChampionIds() {
    return freeChampionIds;
  }

  public void setFreeChampionIds(List<Integer> freeChampionIds) {
    this.freeChampionIds = freeChampionIds;
  }

  public ChampionV3ChampionInfo maxNewPlayerLevel(Integer maxNewPlayerLevel) {
    this.maxNewPlayerLevel = maxNewPlayerLevel;
    return this;
  }

   /**
   * Get maxNewPlayerLevel
   * @return maxNewPlayerLevel
  **/
  @ApiModelProperty(value = "")
  public Integer getMaxNewPlayerLevel() {
    return maxNewPlayerLevel;
  }

  public void setMaxNewPlayerLevel(Integer maxNewPlayerLevel) {
    this.maxNewPlayerLevel = maxNewPlayerLevel;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChampionV3ChampionInfo championV3ChampionInfo = (ChampionV3ChampionInfo) o;
    return Objects.equals(this.freeChampionIdsForNewPlayers, championV3ChampionInfo.freeChampionIdsForNewPlayers) &&
        Objects.equals(this.freeChampionIds, championV3ChampionInfo.freeChampionIds) &&
        Objects.equals(this.maxNewPlayerLevel, championV3ChampionInfo.maxNewPlayerLevel);
  }

  @Override
  public int hashCode() {
    return Objects.hash(freeChampionIdsForNewPlayers, freeChampionIds, maxNewPlayerLevel);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChampionV3ChampionInfo {\n");
    
    sb.append("    freeChampionIdsForNewPlayers: ").append(toIndentedString(freeChampionIdsForNewPlayers)).append("\n");
    sb.append("    freeChampionIds: ").append(toIndentedString(freeChampionIds)).append("\n");
    sb.append("    maxNewPlayerLevel: ").append(toIndentedString(maxNewPlayerLevel)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

