/*
 * Riot API
 *  OpenAPI/Swagger version of the [Riot API](https://developer.riotgames.com/). Automatically generated daily. ## Download OpenAPI Spec File The following versions of the Riot API spec file are available: - `openapi-3.0.0.json` ([download file](../openapi-3.0.0.json), [view ui](?openapi-3.0.0.json)) - `openapi-3.0.0.min.json` ([download file](../openapi-3.0.0.min.json), [view ui](?openapi-3.0.0.min.json)) - `openapi-3.0.0.yml` ([download file](../openapi-3.0.0.yml), [view ui](?openapi-3.0.0.yml)) - `openapi-3.0.0.min.yml` ([download file](../openapi-3.0.0.min.yml), [view ui](?openapi-3.0.0.min.yml)) - `swaggerspec-2.0.json` ([download file](../swaggerspec-2.0.json), [view ui](?swaggerspec-2.0.json)) - `swaggerspec-2.0.min.json` ([download file](../swaggerspec-2.0.min.json), [view ui](?swaggerspec-2.0.min.json)) - `swaggerspec-2.0.yml` ([download file](../swaggerspec-2.0.yml), [view ui](?swaggerspec-2.0.yml)) - `swaggerspec-2.0.min.yml` ([download file](../swaggerspec-2.0.min.yml), [view ui](?swaggerspec-2.0.min.yml)) ## Source Code Source code on [GitHub](https://github.com/MingweiSamuel/riotapi-schema). Pull requests welcome! ## Automatically Generated Rebuilt on [Travis CI](https://travis-ci.org/MingweiSamuel/riotapi-schema/builds) daily. *** 
 *
 * OpenAPI spec version: dfa1c0f97b9cc62a43c9fb91daa1b91b3e9485c2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * MatchV4MatchReferenceDto
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2019-07-17T15:57:39.031+02:00")
public class MatchV4MatchReferenceDto {
  @SerializedName("lane")
  private String lane = null;

  @SerializedName("gameId")
  private Long gameId = null;

  @SerializedName("champion")
  private Integer champion = null;

  @SerializedName("platformId")
  private String platformId = null;

  @SerializedName("season")
  private Integer season = null;

  @SerializedName("queue")
  private Integer queue = null;

  @SerializedName("role")
  private String role = null;

  @SerializedName("timestamp")
  private Long timestamp = null;

  public MatchV4MatchReferenceDto lane(String lane) {
    this.lane = lane;
    return this;
  }

   /**
   * Get lane
   * @return lane
  **/
  @ApiModelProperty(value = "")
  public String getLane() {
    return lane;
  }

  public void setLane(String lane) {
    this.lane = lane;
  }

  public MatchV4MatchReferenceDto gameId(Long gameId) {
    this.gameId = gameId;
    return this;
  }

   /**
   * Get gameId
   * @return gameId
  **/
  @ApiModelProperty(value = "")
  public Long getGameId() {
    return gameId;
  }

  public void setGameId(Long gameId) {
    this.gameId = gameId;
  }

  public MatchV4MatchReferenceDto champion(Integer champion) {
    this.champion = champion;
    return this;
  }

   /**
   * Get champion
   * @return champion
  **/
  @ApiModelProperty(value = "")
  public Integer getChampion() {
    return champion;
  }

  public void setChampion(Integer champion) {
    this.champion = champion;
  }

  public MatchV4MatchReferenceDto platformId(String platformId) {
    this.platformId = platformId;
    return this;
  }

   /**
   * Get platformId
   * @return platformId
  **/
  @ApiModelProperty(value = "")
  public String getPlatformId() {
    return platformId;
  }

  public void setPlatformId(String platformId) {
    this.platformId = platformId;
  }

  public MatchV4MatchReferenceDto season(Integer season) {
    this.season = season;
    return this;
  }

   /**
   * Get season
   * @return season
  **/
  @ApiModelProperty(value = "")
  public Integer getSeason() {
    return season;
  }

  public void setSeason(Integer season) {
    this.season = season;
  }

  public MatchV4MatchReferenceDto queue(Integer queue) {
    this.queue = queue;
    return this;
  }

   /**
   * Get queue
   * @return queue
  **/
  @ApiModelProperty(value = "")
  public Integer getQueue() {
    return queue;
  }

  public void setQueue(Integer queue) {
    this.queue = queue;
  }

  public MatchV4MatchReferenceDto role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Get role
   * @return role
  **/
  @ApiModelProperty(value = "")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public MatchV4MatchReferenceDto timestamp(Long timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @ApiModelProperty(value = "")
  public Long getTimestamp() {
    return timestamp;
  }

  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchV4MatchReferenceDto matchV4MatchReferenceDto = (MatchV4MatchReferenceDto) o;
    return Objects.equals(this.lane, matchV4MatchReferenceDto.lane) &&
        Objects.equals(this.gameId, matchV4MatchReferenceDto.gameId) &&
        Objects.equals(this.champion, matchV4MatchReferenceDto.champion) &&
        Objects.equals(this.platformId, matchV4MatchReferenceDto.platformId) &&
        Objects.equals(this.season, matchV4MatchReferenceDto.season) &&
        Objects.equals(this.queue, matchV4MatchReferenceDto.queue) &&
        Objects.equals(this.role, matchV4MatchReferenceDto.role) &&
        Objects.equals(this.timestamp, matchV4MatchReferenceDto.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lane, gameId, champion, platformId, season, queue, role, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchV4MatchReferenceDto {\n");
    
    sb.append("    lane: ").append(toIndentedString(lane)).append("\n");
    sb.append("    gameId: ").append(toIndentedString(gameId)).append("\n");
    sb.append("    champion: ").append(toIndentedString(champion)).append("\n");
    sb.append("    platformId: ").append(toIndentedString(platformId)).append("\n");
    sb.append("    season: ").append(toIndentedString(season)).append("\n");
    sb.append("    queue: ").append(toIndentedString(queue)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

